### ISSUE TITLE
Low Level Diagram

### ISSUE THREAD

**Issue by marvinraydalida** [rlysam/Team04-BSCS-NS-3A-M#2]
- [x] USER
- [x] PASABUY
- [x] PAHIRAM
- [x] POST
- [x] CATEGORY
- [x] MESSAGE CENTER
- [x] FULFILMENT

**Comment by Anyastasia** [comment]
User low-level diagram finalized

**Comment by marvinraydalida** [comment]
Finished Post sub-issue

**Comment by rlysam** [comment]
Finished 11132021

**Comment by rlysam** [comment]
Finished 11132021
